// This file is automatically generated. Do not edit.
export const firebaseConfig = {
  projectId: "studio-783237410-1b5a7",
  appId: "1:417308689690:web:73abee2ca930ad900998a3",
  storageBucket: "studio-783237410-1b5a7.appspot.com",
  apiKey: "AIzaSyAtLI4CYzgy3QfDmw3gITuj2Rhs0lMfKkI",
  authDomain: "studio-783237410-1b5a7.firebaseapp.com",
  messagingSenderId: "417308689690",
};
